# Generated by Django 4.0.4 on 2022-04-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=20, verbose_name='calle')),
                ('localidad', models.CharField(max_length=20, verbose_name='localidad')),
                ('cp', models.IntegerField(verbose_name='cp')),
            ],
        ),
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido')),
                ('dni', models.IntegerField(verbose_name='dni')),
            ],
        ),
        migrations.CreateModel(
            name='profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=20, verbose_name='profesion')),
            ],
        ),
    ]
