# Generated by Django 4.0.4 on 2022-04-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimvt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='direccion',
            new_name='direcciones',
        ),
        migrations.RenameModel(
            old_name='profesion',
            new_name='profesiones',
        ),
    ]
